### ISSUE TITLE
[EVAL] Aligning with oz-eval benchmark

### ISSUE THREAD

**Issue by djmilena** [textintellect/lighteval#2]
## Aligning with oz-eval benchmark
oz-eval is evaluated through the pattern:

```
Pitanje: {question}

Ponuđeni odgovori:
A. {option_a}
B. {option_b}
C. {option_c}
D. {option_d}
E. {option_e}

Krajnji odgovor:
```

Please note that in your `serbian_eval.py` there is
```
 instruction = "Na osnovu sledećeg pitanja, izaberite tačanu opciju iz ponuđenih odgovora.\n"
```
which we are not using and should be avoided when evaluating this dataset. 
In addition, this enumeration is not in line as well:
```
   for i, choice in enumerate(choices):
        query += f"{i}. {choice}\n"
```
since in our case array of letters A-E as shown in the example above.

## Evaluation metadata
- GitHub url: https://github.com/Stopwolf/lighteval/blob/oz-eval/community_tasks/oz_evals.py
- Dataset url: https://huggingface.co/datasets/DjMel/oz-eval

Hope this helps make the changes! We are available for any open question and further info 🤗

**Comment by DeanChugall** [comment]
@djmilena 
should be fixed now.

Can you confirm that is good!?

**Comment by djmilena** [comment]
Looks good
